server:
  port: 8082
  servlet:
    context-path: /app
spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/t1_db
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver