version: '3.8'
name: t1_docker
services:
  wiremock-setup-core:
    image: rodolpheche/wiremock
    container_name: wiremock-setup-core
    ports:
      - "8031:8080"
    volumes:
      - ./wiremock/stubs/__files/:/home/wiremock/__files/
      - ./wiremock/stubs/mappings/:/home/wiremock/mappings/
    command:
      - -verbose
      - -global-response-templating
  postgres:
    container_name: t1_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Europe/Moscow
    ports:
      - "5432:5432"
    build:
      context: ./
      dockerfile: postgres/Dockerfile_postgres
    restart: unless-stopped
    volumes:
      - ./postgres/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql